web:
  build: .
  links:
   - db
  ports:
   - "8080:80"
db:
  image: sameersbn/mysql:latest 
  environment:
   - DB_USER=openemr
   - DB_PASS=openemr
   - DB_NAME=openemr
  ports:
   - "3306:3306"
